services:
  db:
    image: postgres:14.5-bullseye
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NTB_PASSWORD=${NTB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./packages/db/src/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - ntb

volumes:
  pg_data:


networks:
  ntb: {}
